import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Flatpoint",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin", "cyrillic"] }); // Inter для всего сайта
const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  variable: "--font-montserrat", // Используем CSS переменную для Tailwind
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${montserrat.variable}`}>
      <body
        className={`${inter.className} antialiased overflow-x-hidden bg-clean-space`}
      >
        {children}
      </body>
    </html>
  );
}
