import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Flatpoint",
  description: "Generated by create next app",
};

const interTight = Inter_Tight({ subsets: ["latin", "cyrillic"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${interTight.className} antialiased overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
